version: '3'

services:
###> doctrine/doctrine-bundle ###
    redis:
        image: redis:5-alpine
        ports: [6379:6379]
    php:
      image: 'bitnami/php-fpm:latest'
      volumes:
        - ./artifact/dev/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
        - ./artifact/dev/php.conf:/opt/bitnami/php/etc/conf.d/custom.ini
        - .:/app
      depends_on:
        - redis
      deploy:
        resources:
          limits:
            cpus: '8'
            memory: 1024M
          reservations:
            memory: 256M

    nginx:
        image: nginx:stable
        container_name: nginx.local
        ports:
            - "8080:80"
        volumes:
            - ./artifact/dev/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./artifact/dev/original.conf:/etc/nginx/nginx.conf
            - ./var/log/nginx:/var/log/nginx
            - .:/app
        depends_on:
            - php
        links:
            - php:php.local
