version: '3'

services:
###> doctrine/doctrine-bundle ###
    redis:
        image: redis:5-alpine
        ports: [6379:6379]
    php:
      image: 'bitnami/php-fpm:latest'
      volumes:
        - .:/app
      depends_on:
        - redis

    nginx:
        image: nginx:1.11-alpine
        container_name: nginx.local
        ports:
            - "8080:80"
        volumes:
            - ./artifact/dev/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./var/log/nginx:/var/log/nginx
            - .:/app
        depends_on:
            - php
        links:
            - php:php.local
